spring:
  social:
    facebook:
      app:
        id: 579377249444600
        secret: c96125b1b6f8cd6c56d87fb7447968eb

    linkedin:
      app:
        id: 77zu4tf3131uvp
        secret: aZXdAO9y86X1xd4d


    google:
      app:
        id: 179076641433-okgi2ppavasdm2d8g9h88hdfs6ai8i0l.apps.googleusercontent.com
        secret: Qxbm5-C4o0ubNkeo38Kt0sbu

  application:
    name: todo
  datasource:
    url: jdbc:mysql://${app.db.host}:${app.db.port}/todo?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  mail:
    host: smtp.gmail.com
    username: ${app.email}
    password: ${app.password}
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true


server:
  port: ${app.port}

app:
  host: localhost
  #  host: 185.2.103.111
  port: 9606
  email: todoApp.iba@gmail.com
  password: todoApp123
  emailhost: 185.2.103.111
  db:
    #    host: localhost
    host: db-todo
    port: 3306